---
- name: Update apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
  
- name: Install required packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: latest 
    update_cache: yes

- name: Add Docker's GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

- name: Update apt packages again
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest
    notify:
     - Docker restart

- name: Add user to Docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  become: yes